Repository nextcloud/notes, pull requests merged in 2018-07, with the labels that each got.

#215 fix XML validation: remove ocsid
  appinfo/info.xml
Labels: bug

#216 fix: database index is too long
  appinfo/database.xml
Labels: bug

#219 show error message if notes folder has errors
  controller/pagecontroller.php
  service/notesfolderexception.php
  service/notesservice.php
Labels: enhancement

#207 Make notes path configurable
  appinfo/routes.php
  controller/settingscontroller.php
  js/app/controllers/notessettingscontroller.js
  js/public/app.min.js
  js/public/app.min.js.map
  service/notesservice.php
  service/settingsservice.php
  templates/main.php
Labels: design, enhancement

#223 add setting for default file suffix
  controller/settingscontroller.php
  css/notes.css
  js/app/controllers/notessettingscontroller.js
  js/public/app.min.js
  js/public/app.min.js.map
  service/notesservice.php
  service/settingsservice.php
  templates/main.php
Labels: enhancement

#213 fix: navigation-toggle disappeared in some situations
  css/notes.css
Labels: bug, design
