Repository nextcloud/notes, pull requests merged in 2020-01, with the labels that each got.

#427 checkmark design
  src/components/EditorEasyMDE.vue
Labels: design, feature: EasyMDE

#439 Up max-version to 19 for latest server master
  appinfo/info.xml
Labels: bug

#441 update dependencies
  package-lock.json
  package.json
Labels: dependencies
