Repository nextcloud/notes, pull requests merged in 2020-05, with the labels that each got.

#500 Preview mode: show empty table rows
  src/components/EditorMarkdownIt.vue
Labels: feature: Markdown-it

#491 API documentation for API v1
  README.md
  appinfo/info.xml
  docs/api/README.md
  docs/api/v1.md
Labels: feature: API

#502 release version 3.3.0
  CHANGELOG.md
  appinfo/info.xml
Labels: maintenance

#513 relax autosave
  src/components/Note.vue
Labels: feature: editor

#515 show empty categories in Sidebar
  lib/Controller/NotesApiController.php
  lib/Controller/NotesController.php
  lib/Service/NotesService.php
  src/NotesService.js
  src/store.js
Labels: feature: backend, feature: sidebar

#517 Category list: fix notes count
  src/components/NavigationCategoriesItem.vue
Labels: feature: app navigation

#518 API: filter notes by category
  composer.json
  docs/api/v1.md
  lib/Application.php
  lib/Controller/NotesApiController.php
  tests/api/APIv1Test.php
  tests/api/AbstractAPITest.php
  tests/api/CommonAPITest.php
Labels: feature: API

#522 New icon for Notes app
  img/favicon-mask.svg
  img/favicon-touch.png
  img/favicon-touch.svg
  img/favicon.ico
  img/favicon.png
  img/favicon.svg
  img/notes.svg
Labels: design, enhancement

#527 update dependencies
  package-lock.json
  package.json
Labels: maintenance
