Repository nextcloud/notes, pull requests merged in 2021-11, with the labels that each got.

#772 Update npm and node engines versions
  package.json
Labels: dependencies

#773 update dependencies
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  package-lock.json
  package.json
  src/components/ConflictSolution.vue
Labels: dependencies, maintenance

#774 lint with node 14 and npm 7
  .github/workflows/lint.yml
Labels: maintenance

#775 keep Sidebar open when open other note
  src/components/Note.vue
Labels: feature: sidebar, feature: editor

#776 release 4.2.0
  CHANGELOG.md
  appinfo/info.xml
Labels: maintenance
