Repository nextcloud/notes, pull requests merged in 2023-11, with the labels that each got.

#1004 Sidebar: removed
  package-lock.json
  package.json
  src/App.vue
  src/components/NoteItem.vue
  src/components/NotePlain.vue
  src/components/NoteRich.vue
  src/components/NotesList.vue
  src/components/Sidebar.vue
  src/router.js
  src/store/app.js
Labels: enhancement

#1146 Feature/share single note
  lib/AppInfo/Application.php
  lib/AppInfo/BeforeShareCreatedListener.php
  lib/Controller/PageController.php
  lib/Service/Note.php
  lib/Service/NoteUtil.php
  src/NotesService.js
  src/components/NoteItem.vue
  src/components/NotePlain.vue
  src/components/NoteRich.vue
  tests/phan-config.php
  tests/stubs/ocp.php
Labels: 3. to review

#1153 Avoid throwing on other share types than user
  lib/AppInfo/Application.php
  lib/AppInfo/BeforeShareCreatedListener.php
Labels: 3. to review

#1164 fix: Scrolling on mobile and proper alignment of the back button/menubar
  src/components/NoteRich.vue
  src/components/NotesView.vue
Labels: bug, 3. to review
