Repository nextcloud/notes, pull requests merged in 2023-12, with the labels that each got.

#1174 fix: Resolve file list dependency of the sidebar on Nextcloud <= 27
  src/main.js
Labels: bug, 3. to review

#1182 fix: Avoid using constant that is not available on 25
  lib/Service/NoteUtil.php
Labels: bug, 3. to review

#1192 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
Labels: dependencies, automated, 3. to review

#1194 chore: Bump max-version of PHP to 8.3
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/AppInfo/BeforeShareCreatedListener.php
  lib/AppInfo/DashboardWidget.php
  lib/Controller/NotesController.php
  tests/phan-config.php
Labels: bug, 3. to review

#1191 Add bidi support
  css/notes.css
  package-lock.json
  package.json
  src/App.vue
  src/components/EditorEasyMDE.vue
  src/components/EditorMarkdownIt.vue
  src/components/HelpMobile.vue
  src/components/Modal/EditorHint.vue
  src/components/NotePlain.vue
  src/components/NoteRich.vue
  src/components/NotesView.vue
Labels: enhancement, 3. to review
