Repository nextcloud/notes, pull requests merged in 2023-05, with the labels that each got.

#1031 fix: Proper response for attachment endpoint
  lib/Controller/NotesController.php
Labels: bug

#1021 Three column layout (rebased/squashed)
  src/App.vue
  src/components/CategoriesList.vue
  src/components/EditorEasyMDE.vue
  src/components/HelpMobile.vue
  src/components/NavigationList.vue
  src/components/Note.vue
  src/components/NoteItem.vue
  src/components/NoteRich.vue
  src/components/NotesCaption.vue
  src/components/NotesList.vue
  src/components/NotesView.vue
  src/components/Sidebar.vue
  src/router.js
  src/store/app.js
  src/store/notes.js
Labels: enhancement, design

#1043 Use the color-primary-element* variables
  src/components/CategoriesList.vue
  src/components/EditorEasyMDE.vue
  src/components/Sidebar.vue
Labels: bug, design

#1048 fix: setting button spacing
  src/App.vue
Labels: bug

#1047 fix: Wrap renaming of notes through autotile in locking context
  lib/Controller/NotesController.php
  lib/Service/Note.php
Labels: bug
