Repository nextcloud/notes, pull requests merged in 2024-07, with the labels that each got.

#1281 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#1321 chore: Bump minimum supported versions to 28
  appinfo/info.xml
Labels: 3. to review, technical debt

#1322 fix: Switch to vue-frag instead of vue-fragment to avoid errors during delete
  package-lock.json
  package.json
  src/components/CategoriesList.vue
  src/components/HelpMobile.vue
  src/components/NoteItem.vue
Labels: bug, 3. to review

#1324 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
Labels: dependencies, automated, 3. to review

#1323 fix: apply css variable --default-clickable-area
  src/components/Dashboard.vue
  src/components/NotePlain.vue
  src/components/NoteRich.vue
  src/components/NotesCaption.vue
Labels: 3. to review

#1320 fix/shared notes
  lib/AppInfo/BeforeShareCreatedListener.php
  lib/Service/NoteUtil.php
  lib/Service/NotesService.php
  lib/Service/SettingsService.php
Labels: bug, 3. to review
