Repository nextcloud/notes, pull requests merged in 2024-12, with the labels that each got.

#1410 Migrate notes search to NcTextField with clear button
  src/components/NotesView.vue
Labels: feature: app navigation, 3. to review

#1432 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#1415 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1456 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
