Repository nextcloud/notes, pull requests merged in 2024-10, with the labels that each got.

#1387 fix: Adjust note item size to be one line
  src/components/NoteItem.vue
Labels: bug, design, 3. to review

#1377 feat: migrate to files:node:updated
  src/components/NoteRich.vue
Labels: 3. to review

#1389 Move to more standard CI pipelines
  .github/workflows/appstore-build-publish.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
  .github/workflows/node.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/reuse.yml
  .github/workflows/test.yml
  .gitignore
  .nextcloudignore
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/AppInfo/BeforeShareCreatedListener.php
  lib/AppInfo/BeforeTemplateRenderedListener.php
  lib/AppInfo/DashboardWidget.php
  lib/AppInfo/NotesHooks.php
  lib/AppInfo/SearchProvider.php
  lib/Controller/Helper.php
  lib/Controller/NotesApiController.php
  lib/Controller/NotesController.php
  lib/Controller/PageController.php
  lib/Controller/SettingsController.php
  lib/Service/MetaService.php
  lib/Service/Note.php
  lib/Service/NoteUtil.php
  lib/Service/NotesService.php
  lib/Service/SettingsService.php
  lib/Service/Util.php
  psalm.xml
  tests/api/APIv1Test.php
  tests/api/AbstractAPITest.php
  tests/api/CapabilitiesTest.php
  tests/api/CommonAPITest.php
  tests/nextcloud-version.php
  tests/psalm-baseline.xml
Labels: 3. to review, technical debt
